### PR TITLE
Allow users to opt-out of sending the UDP ping and improve error handling when the sendto syscall fails

### PR DESCRIPTION
**Pull request by clemensg**
Allow users to opt-out of sending the UDP ping and improve error handling when the sendto syscall fails.

This is a first attempt to improve the metrics opt-out and rescue the exceptions thrown when the sendto syscall fails, for example when it is blocked by a firewall or if there is no Internet connectivity.

I changed the boolean preference to three symbols: none, ping and full

See also: https://github.com/capistrano/stats/pull/1

Signed-off-by: Clemens Gruber clemensgru@gmail.com

### CODE REVIEW

**Comment by leehambley** [comment]
Hey @clemensg thanks for the promptly formulated PR. 

I think this misses the case that there's something other than `:full` or `:ping` in the `.capistrano/metrics` file, incase someone has already answered the prompt. It seems like [this line](https://github.com/capistrano/stats/pull/2/files#diff-c3f52e8ec4eed5d045df8e632fe2a00cR18) will cause a problem there, as we'll end up with `:true` or `:false` for these people.

I'm also not sure if the exception list [here](https://github.com/capistrano/stats/pull/2/files#diff-c3f52e8ec4eed5d045df8e632fe2a00cR26) is enough to catch all the cases that [`socket.send()`](https://github.com/capistrano/stats/blob/e6724619694ae4a1cf5f74d33c458377e1236b7e/gem/lib/capistrano-stats/metric-collector.rb#L23) can possibly raise, this is a common failing of Ruby (see the 47 different things that the HTTP class and it's friend can raise under various conditions, none of which share an exception/error namespace), maybe it's sufficient to `rescue` everything? We really don't want metrics to block the deploy under any case.

**Comment by leehambley** [comment]
Looks good @clemensg, let me do some testing, and I'll try and get that released in the morning (Hamburg time).

At the same time, I will properly fix the server to properly collect the "optouts" (`:ping`), and I might yet tweak the wording of your messages in the PR.

**Comment by clemensg** [comment]
Nice. Thank you!

**Comment by cpg** [comment]
This is still in place, attempting to send stuff. In a restricted network, this prevents from deployment with:

```
The deploy has failed with an error: Host is down - sendto(2) for "metrics.capistranorb.com" port 1200
```

earlier a few days ago, I answered no to the metrics question (which should be asked in the first place -- it messes with tty in the middle of a deployment and breaks CI, etc.), and my .capistrano/metrics contains "false" (without a newline). Therefore, it should not even attempt to contact the metrics sever to begin with.

Also, where is the dasboard where all these stats can be seen? it's not at http://metrics.capistranorb.com (or w/https).

**Comment by leehambley** [comment]
> Therefore, it should not even attempt to contact the metrics sever to begin with. 

Agreed, and we have a PR here which solves a big piece of that problem, but not the whole story. Unfortunately with a young child at home, I don't have free time in the evenings to work on FOSS anymore, and when I do find some time, I will make the fixes I committed to making here with @clemensg.

> Also, where is the dasboard where all these stats can be seen? it's not at http://metrics.capistranorb.com (or w/https).

There is none, yet, see above, also as you can see from this repository which contains everything about the metrics, there is no server, yet.

If you don't like the new version of Capistrano, with the new metrics, roll back and use the old one, this is the freedom you enjoy whilst enjoying software for which you paid nothing. No warranty, no right to be annoyed when I make a change which causes you an inconvenience. The changes were documented, announced, clearly marked, workarounds are published and I am working on a fix, in what little time I have to dedicate to writing software for which I earn nothing.

**Comment by leehambley** [comment]
> which should be asked in the first place -- it messes with tty in the middle of a deployment and breaks CI, etc

There is no prompt if `stdin` is not a `tty` if you have configured your CI server to emulate a tty for something like vanity colour printing, then you are responsible, or your CI is broken by design.

**Pull request merged**
